drop table if exists test_hidden purge;
drop domain if exists status_d;

create domain status_d as enum
  ( initializing = default_ = 1, analyzing, curating, finalized, deprecated )
  default on null for insert and update 1;


create table test_hidden (
  id          int generated by default on null as identity primary key,
  some_state  status_d invisible,
  s_date      date default on null for insert only sysdate not null
);

insert into test_hidden (s_date) values
 (date '1999-01-01');

insert into test_hidden (some_state,s_date)
select mod(level - 1,5) + 1, trunc(sysdate) + level
from dual connect by level <= 200;

commit;
